"""
Project 4: Smart FAQ Chatbot (RAG-Based System)
Calder AI/ML Internship

Retrieval-Augmented Generation pipeline:
  1. Knowledge base → chunked & embedded (TF-IDF vectors stored in a vector index)
  2. User query → embedded → top-K retrieval via cosine similarity
  3. Retrieved context + query → answer generated by language model (Claude API)

Design choices:
  - TF-IDF embeddings (no external embedding API needed; FAISS-compatible interface)
  - In-memory vector store with numpy-style similarity search
  - Claude claude-sonnet-4-20250514 for answer generation
  - Fallback response when no relevant context found
"""

import json
import math
import re
import os
import urllib.request
import urllib.error
from collections import Counter
from pathlib import Path


# ─────────────────────────────────────────────
# Knowledge Base
# ─────────────────────────────────────────────

KNOWLEDGE_BASE = [
    # Company
    "Calder is a technology company based at NASTP, Rawalpindi, Pakistan. The company's mission is to help modern businesses work smarter and move faster by removing complexity from everyday work. Calder's vision is a world where businesses run effortlessly.",

    # Products & Features
    "Calder offers an AI-powered workflow automation platform that includes task management, team collaboration, document management, and intelligent reporting. The platform is accessible via web, mobile, and desktop applications.",
    "Calder integrates with major tools including Slack, Microsoft Teams, Google Workspace, Microsoft 365, Asana, Trello, Jira, Salesforce, and HubSpot. Integrations are available through native connectors or the REST API.",
    "The Calder dashboard provides real-time analytics, project tracking, team workload visibility, and automated status updates. Custom dashboards can be built using the drag-and-drop builder.",

    # Pricing
    "Calder offers three pricing tiers: Starter (free, up to 5 users, core features), Professional ($29/user/month, unlimited users, advanced automation, priority support), and Enterprise (custom pricing, SSO, dedicated support, SLA guarantees, on-premise option).",
    "All Calder plans include a 14-day free trial with access to Professional features. No credit card is required to start the trial. After trial expiry, accounts revert to the Starter plan unless upgraded.",
    "Annual billing is available at a 20% discount compared to monthly billing. Non-profit organizations qualify for a 30% discount. Educational institutions can apply for academic pricing.",

    # Security & Compliance
    "Calder uses AES-256 encryption for data at rest and TLS 1.3 for all data in transit. The platform is SOC 2 Type II certified, GDPR compliant, and follows ISO 27001 standards. Penetration testing is conducted quarterly.",
    "User data is never sold to third parties. Calder operates data centers in the EU and Asia-Pacific regions with 99.9% uptime SLA. Data residency options are available for Enterprise customers.",
    "Calder supports multi-factor authentication (MFA), SAML 2.0 SSO, role-based access control (RBAC), and detailed audit logs. IP whitelisting and session timeout controls are available on Professional and Enterprise plans.",

    # API & Developers
    "The Calder REST API supports Python, JavaScript/Node.js, Ruby, PHP, Go, and Java via official SDKs. The API follows OpenAPI 3.0 specification. Rate limits: 1,000 requests/minute on Professional, 10,000 on Enterprise.",
    "Webhooks are supported for real-time event notifications. Calder also provides a GraphQL API (beta) for flexible data querying. API keys can be managed in Settings > Developer > API Keys.",
    "The Calder developer documentation is available at docs.calder.ai. It includes quickstart guides, API reference, SDK examples, webhook event catalog, and a Postman collection for testing.",

    # Support
    "Calder provides support via email (support@calder.ai), phone (+92 349 5904995), and live chat. Business hours are Monday to Friday, 9 AM to 6 PM PKT. Enterprise customers receive 24/7 dedicated support.",
    "The Calder help center at help.calder.ai contains over 500 articles, video tutorials, and community forums. Users can submit support tickets directly from within the application.",
    "Calder offers onboarding services including live training sessions, implementation consulting, and dedicated customer success managers for Enterprise accounts.",

    # Account Management
    "To reset your password, click 'Forgot Password' on the login page and enter your registered email. A secure reset link is sent immediately and expires in 24 hours.",
    "To cancel a subscription, go to Account Settings > Billing > Cancel Subscription. Subscriptions remain active until the end of the current billing period. Data is retained for 90 days post-cancellation.",
    "Data can be exported from Account Settings > Data Export. Supported formats include CSV, JSON, Excel, and PDF. Bulk exports are processed asynchronously and available via download link within 30 minutes.",
    "Users can invite team members from Settings > Team Management. Role options include Admin, Manager, Member, and Viewer. Each role has configurable permission sets.",

    # Performance & Reliability
    "Calder maintains a public status page at status.calder.ai showing real-time platform health and historical uptime. Planned maintenance windows are announced 72 hours in advance.",
    "The Calder mobile app is available for iOS (App Store) and Android (Google Play). It supports offline mode for viewing tasks and documents, with automatic sync when connectivity is restored.",
]


# ─────────────────────────────────────────────
# Text Preprocessing
# ─────────────────────────────────────────────

STOP_WORDS = {
    "a", "an", "the", "is", "it", "in", "on", "at", "to", "do", "i",
    "my", "me", "we", "our", "you", "your", "can", "will", "be", "am",
    "are", "was", "were", "has", "have", "had", "this", "that", "of",
    "for", "with", "about", "from", "or", "and", "not", "but", "so",
    "if", "as", "by", "its", "been", "into", "each", "also", "any",
    "all", "via", "per",
}


def preprocess(text: str) -> list[str]:
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return [t for t in text.split() if t not in STOP_WORDS and len(t) > 1]


# ─────────────────────────────────────────────
# In-Memory Vector Store (FAISS-compatible interface)
# ─────────────────────────────────────────────

class VectorStore:
    """Simple in-memory TF-IDF vector store with cosine similarity search."""

    def __init__(self):
        self.documents: list[str] = []
        self.vectors: list[dict[str, float]] = []
        self.idf: dict[str, float] = {}

    def _build_idf(self):
        N = len(self.documents)
        tokenized = [preprocess(d) for d in self.documents]
        vocab = {w for toks in tokenized for w in toks}
        for word in vocab:
            df = sum(1 for toks in tokenized if word in toks)
            self.idf[word] = math.log((N + 1) / (df + 1)) + 1

    def _tfidf_vector(self, tokens: list[str]) -> dict[str, float]:
        tf = Counter(tokens)
        total = len(tokens) if tokens else 1
        return {w: (c / total) * self.idf.get(w, 0) for w, c in tf.items()}

    def add_documents(self, documents: list[str]):
        """Embed and store documents."""
        self.documents = list(documents)
        self._build_idf()
        tokenized = [preprocess(d) for d in self.documents]
        self.vectors = [self._tfidf_vector(toks) for toks in tokenized]

    def search(self, query: str, top_k: int = 3) -> list[dict]:
        """Return top-K most relevant documents with scores."""
        q_tokens = preprocess(query)
        q_vec = self._tfidf_vector(q_tokens)

        scores = []
        for i, vec in enumerate(self.vectors):
            dot = sum(q_vec.get(k, 0) * vec.get(k, 0) for k in q_vec)
            na = math.sqrt(sum(v**2 for v in q_vec.values()))
            nb = math.sqrt(sum(v**2 for v in vec.values()))
            sim = dot / (na * nb) if na and nb else 0.0
            scores.append((i, sim))

        scores.sort(key=lambda x: x[1], reverse=True)
        return [
            {"document": self.documents[i], "score": round(s, 4)}
            for i, s in scores[:top_k]
            if s > 0
        ]


# ─────────────────────────────────────────────
# LLM Response Generator (Claude API)
# ─────────────────────────────────────────────

CLAUDE_API_URL = "https://api.anthropic.com/v1/messages"
CLAUDE_MODEL = "claude-sonnet-4-20250514"


def call_claude_api(system_prompt: str, user_message: str, api_key: str) -> str:
    """Call the Claude API and return the text response."""
    payload = {
        "model": CLAUDE_MODEL,
        "max_tokens": 512,
        "system": system_prompt,
        "messages": [{"role": "user", "content": user_message}],
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        CLAUDE_API_URL,
        data=data,
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = json.loads(resp.read().decode("utf-8"))
            return body["content"][0]["text"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        raise RuntimeError(f"Claude API error {e.code}: {error_body}")


# ─────────────────────────────────────────────
# RAG Chatbot
# ─────────────────────────────────────────────

SYSTEM_PROMPT = """You are a helpful assistant for Calder, a business productivity platform.
Answer questions accurately and concisely based ONLY on the provided context.
If the context does not contain enough information to answer the question, say so clearly and politely.
Do not make up information. Keep answers focused and professional.
Format your response in plain text without markdown unless specifically helpful."""

FALLBACK_RESPONSE = (
    "I'm sorry, I couldn't find relevant information to answer your question. "
    "Please contact our support team at support@calder.ai or call +92 349 5904995 for assistance."
)


class RAGChatbot:
    SIMILARITY_THRESHOLD = 0.02
    TOP_K = 3

    def __init__(self, api_key: str | None = None):
        self.api_key = api_key or os.environ.get("ANTHROPIC_API_KEY", "")
        self.vector_store = VectorStore()
        self.conversation_history: list[dict] = []
        self._build_knowledge_base()

    def _build_knowledge_base(self):
        """Index the knowledge base into the vector store."""
        self.vector_store.add_documents(KNOWLEDGE_BASE)
        print(f"✓ Knowledge base indexed | {len(KNOWLEDGE_BASE)} documents")

    def add_documents(self, documents: list[str]):
        """Add additional documents to the knowledge base at runtime."""
        all_docs = KNOWLEDGE_BASE + documents
        self.vector_store.add_documents(all_docs)

    def _retrieve_context(self, query: str) -> list[dict]:
        """Retrieve relevant documents for a query."""
        results = self.vector_store.search(query, top_k=self.TOP_K)
        return [r for r in results if r["score"] >= self.SIMILARITY_THRESHOLD]

    def _build_prompt(self, query: str, context_docs: list[dict]) -> str:
        """Build the prompt with retrieved context."""
        context_text = "\n\n".join(
            f"[Context {i+1}]: {doc['document']}"
            for i, doc in enumerate(context_docs)
        )
        return (
            f"Context:\n{context_text}\n\n"
            f"User Question: {query}\n\n"
            f"Please answer based on the context above."
        )

    def chat(self, query: str) -> dict:
        """
        Process a user query through the RAG pipeline.

        Returns:
            dict with: answer, retrieved_docs, used_llm, query
        """
        if not query.strip():
            return {"answer": "Please enter a valid question.", "retrieved_docs": [], "used_llm": False}

        # Step 1: Retrieve
        retrieved = self._retrieve_context(query)

        # Step 2: Fallback if no relevant context
        if not retrieved:
            return {
                "answer": FALLBACK_RESPONSE,
                "retrieved_docs": [],
                "used_llm": False,
                "query": query,
            }

        # Step 3: Generate with LLM if API key available
        if self.api_key:
            try:
                prompt = self._build_prompt(query, retrieved)
                answer = call_claude_api(SYSTEM_PROMPT, prompt, self.api_key)
                used_llm = True
            except Exception as e:
                # Graceful fallback: return best retrieved document
                answer = f"[LLM unavailable: {e}]\n\n{retrieved[0]['document']}"
                used_llm = False
        else:
            # No API key: return best retrieved document as answer
            answer = retrieved[0]["document"]
            used_llm = False

        self.conversation_history.append({"role": "user", "content": query})
        self.conversation_history.append({"role": "assistant", "content": answer})

        return {
            "answer": answer,
            "retrieved_docs": retrieved,
            "used_llm": used_llm,
            "query": query,
        }

    def run_cli(self):
        """Interactive CLI for the RAG chatbot."""
        print("=" * 60)
        print("  Calder RAG Chatbot  |  Type 'exit' to quit")
        if not self.api_key:
            print("  [Note: No API key set — using retrieval-only mode]")
            print("  Set ANTHROPIC_API_KEY env var to enable LLM generation")
        print("=" * 60)

        while True:
            try:
                query = input("\nYou: ").strip()
            except (EOFError, KeyboardInterrupt):
                break

            if not query:
                continue
            if query.lower() in {"exit", "quit", "bye"}:
                print("Bot: Goodbye!")
                break

            result = self.chat(query)
            print(f"\nBot: {result['answer']}")

            if result["retrieved_docs"]:
                print(f"\n[Retrieved {len(result['retrieved_docs'])} docs | "
                      f"LLM: {'yes' if result['used_llm'] else 'no (retrieval-only)'}]")

        print("\nSession ended.")


# ─────────────────────────────────────────────
# Entry Point
# ─────────────────────────────────────────────

if __name__ == "__main__":
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    bot = RAGChatbot(api_key=api_key)
    bot.run_cli()
